# Generated by Django 6.0.7 on 2026-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Water in Liters')),
                ('date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
