# Generated by Django 6.0.7 on 2026-07-24 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Enter weight in kg')),
                ('height', models.FloatField(help_text='Enter height in cm')),
                ('goal', models.CharField(choices=[('Loss', 'Weight Loss'), ('Gain', 'Weight Gain'), ('Maintain', 'Maintain Weight')], default='Maintain', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
