# Generated by Django 6.0.7 on 2026-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='target_date',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
        migrations.AddField(
            model_name='goal',
            name='current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='target',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
