# Generated by Django 6.0.7 on 2026-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_remove_goal_goal_type_goal_category_goal_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='unit',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Muscle Gain', 'Muscle Gain'), ('Maintain Weight', 'Maintain Weight')], default='Weight Loss', max_length=50),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_weight',
            field=models.FloatField(default=0),
        ),
    ]
