# Generated by Django 6.0.7 on 2026-07-23 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_rename_target_date_goal_deadline_remove_goal_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='deadline',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='current',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Muscle Gain', 'Muscle Gain'), ('Maintain Fitness', 'Maintain Fitness')], default='Maintain Fitness', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 7, 24)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target',
            field=models.FloatField(),
        ),
    ]
