# Generated by Django 6.0.7 on 2026-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_rename_deadline_goal_end_date_remove_goal_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_type',
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Muscle Gain', 'Muscle Gain'), ('Water Intake', 'Water Intake'), ('Steps', 'Steps'), ('Workout', 'Workout'), ('Calories', 'Calories')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(default='Weight Loss', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
            preserve_default=False,
        ),
    ]
