# Generated by Django 6.0.7 on 2026-09-26 14:47

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_waterintake_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target_liters', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(10.0)])),
                ('interval_minutes', models.PositiveSmallIntegerField(choices=[(30, 'Every 30 minutes'), (60, 'Every hour'), (90, 'Every 90 minutes'), (120, 'Every 2 hours'), (180, 'Every 3 hours'), (240, 'Every 4 hours')], default=120)),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('end_time', models.TimeField(default=datetime.time(22, 0))),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
