# Generated by Django 6.0.7 on 2026-09-26 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_waterremindersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterremindersettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterremindersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waterremindersettings',
            name='interval_minutes',
            field=models.PositiveSmallIntegerField(choices=[(30, 'Every 30 minutes'), (60, 'Every hour'), (120, 'Every 2 hours')], default=120),
        ),
    ]
