# Generated by Django 6.0.7 on 2026-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength Training'), ('Yoga', 'Yoga'), ('HIIT', 'HIIT'), ('Running', 'Running')], max_length=30)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('calories_burned', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
