# Generated by Django 6.0.7 on 2026-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Yoga', 'Yoga'), ('Running', 'Running'), ('Cycling', 'Cycling')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
