# Generated by Django 6.0.7 on 2026-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workout_calories_burned_alter_workout_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength Training'), ('Yoga', 'Yoga'), ('HIIT', 'HIIT'), ('Flexibility', 'Flexibility')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(choices=[('Running', 'Running'), ('Walking', 'Walking'), ('Cycling', 'Cycling'), ('Push Ups', 'Push Ups'), ('Pull Ups', 'Pull Ups'), ('Squats', 'Squats'), ('Lunges', 'Lunges'), ('Plank', 'Plank'), ('Weight Training', 'Weight Training'), ('HIIT', 'HIIT'), ('Yoga', 'Yoga'), ('Meditation', 'Meditation'), ('Swimming', 'Swimming'), ('Dancing', 'Dancing'), ('Jump Rope', 'Jump Rope'), ('Other', 'Other')], max_length=100),
        ),
    ]
