# Generated by Django 6.0.7 on 2026-07-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_exercise_yoga_workout_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
    ]
